image: openjdk:11-jre-slim-stretch

stages:
  - build
  - test
  - validate
  - reports

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/*
    expire_in: 1 day

test:
  stage: test
  script: ./gradlew check jacocoTestReport coverageReport
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/reports/tests/*
      - build/reports/jacoco/*
    expire_in: 1 day

validate:
  stage: validate
  script: ./gradlew checkQualityMain
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/reports/checkstyle/*
      - build/reports/pmd/*
      - build/reports/spotbugs/*
    expire_in: 1 day

reports:owasp:
  stage: reports
  script: ./gradlew dependencyCheckAnalyze
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/reports/dependency-check-report.html
    expire_in: 1 day
  only:
    refs:
      - master

reports:license:
  stage: reports
  script: ./gradlew generateLicenseReport
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/reports/dependency-license/*
    expire_in: 1 day
  only:
    refs:
      - master

reports:dependencyUpdates:
  stage: reports
  script: ./gradlew dependencyUpdates
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/dependencyUpdates/report.txt
    expire_in: 1 day
  only:
    refs:
      - master