---
spring:
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  jpa:
    open-in-view: false
    properties:
      generate-ddl: false
      database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
